name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        avro: [1.9.2,1.10.0]
        include:
          # Specify version of avro to be latest TAG
          - avro: 1.10.0
            latest: true
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: brandonstubbs/avro-tools:${{ matrix.avro }}
          build-args: |
            AVRO_VERSION=${{ matrix.avro  }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
