name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        avro: [1.9.2,1.10.0]
        include:
          # Specify version of avro to be latest TAG
          - avro: 1.10.0
            latest: brandonstubbs/avro-tools:latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            brandonstubbs/avro-tools:${{ matrix.avro }}
            ${{ matrix.latest }}
          build-args: |
            AVRO_VERSION=${{ matrix.avro }}
